name: BuildNGL

on: [push, pull_request]

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    
    - name: install vcpkg
      run : |
        git clone --depth 1  https://github.com/microsoft/vcpkg ~/vcpkg 
        cd ~/vcpkg 
        ./bootstrap-vcpkg.sh
        ./vcpkg install fmt 
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake ..
               
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        cd build
        threads=`nproc`
        cmake --build .  --parallel $threads
    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: |
        cd build
        ./fmt